/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Created:		Jun 28, 2020
 *			Eugene G <yujin@Eugenes-MBP>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.12.0\n"
	"                  Configured on: Sun Jun 28 15:15:07 PDT 2020\n"
	"                  Configured by: yujin@Eugenes-MBP\n"
	"                    Host system: i386-apple-darwin\n"
	"              Uname information: Darwin Eugenes-MBP 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /Users/yujin/Desktop/ios-hdf5-examples/scri/hdf5-1.12-master/output/x86_64\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: debug\n"
	"              Debugging Symbols: yes\n"
	"                        Asserts: yes\n"
	"                      Profiling: no\n"
	"             Optimization Level: debug\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: static\n"
	"  Statically Linked Executables: \n"
	"                        LDFLAGS: -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk\n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: -lz -ldl -lm \n"
	"                       Archiver: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar\n"
	"                       AR_FLAGS: cr\n"
	"                         Ranlib: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang\n"
	"                       CPPFLAGS: -arch x86_64  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -miphoneos-version-min=13.2\n"
	"                    H5_CPPFLAGS:   -UNDEBUG -DH5AC_DEBUG -DH5B2_DEBUG -DH5CX_DEBUG -DH5D_DEBUG -DH5F_DEBUG -DH5HL_DEBUG -DH5I_DEBUG -DH5O_DEBUG -DH5S_DEBUG -DH5ST_DEBUG -DH5T_DEBUG -DH5Z_DEBUG -DH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: \n"
	"                        C Flags: -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -miphoneos-version-min=13.2\n"
	"                     H5 C Flags:     \n"
	"                     AM C Flags: \n"
	"               Shared C Library: no\n"
	"               Static C Library: yes\n"
	"\n"
	"\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"                           Java: no\n"
	"\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                   Parallel HDF5: no\n"
	"Parallel Filtered Dataset Writes: no\n"
	"              Large Parallel I/O: no\n"
	"              High-level library: yes\n"
	"                Build HDF5 Tests: yes\n"
	"                Build HDF5 Tools: yes\n"
	"                    Threadsafety: no\n"
	"             Default API mapping: v112\n"
	"  With deprecated public symbols: yes\n"
	"          I/O filters (external): deflate(zlib)\n"
	"                             MPE: no\n"
	"                   Map (H5M) API: no\n"
	"                      Direct VFD: no\n"
	"              (Read-Only) S3 VFD: no\n"
	"            (Read-Only) HDFS VFD: no\n"
	"                         dmalloc: no\n"
	"  Packages w/ extra debug output: AC,B2,CX,D,F,HL,I,O,S,ST,T,Z\n"
	"                     API tracing: yes\n"
	"            Using memory checker: no\n"
	" Memory allocation sanity checks: yes\n"
	"          Function stack tracing: no\n"
	"       Strict file format checks: yes\n"
	"    Optimization instrumentation: no\n"
;

